#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage: $0 module_name" >&2
	exit 1
fi

module=$1
device=$1
shift

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}

